<a href="https://colab.research.google.com/github/abhiiyadav2595/Descriptive-Analytics/blob/main/Exp_9_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

In [8]:
np.random.seed(42)

data = {
    'Customer_ID': range(1, 1001),
    'Age': np.random.randint(18, 70, 1000),
    'Annual_Spend': np.random.randint(100, 5000, 1000),
    'Region': np.random.choice(
        ['North', 'South', 'East', 'West'],
        1000
    )
}

df = pd.DataFrame(data)

print("Dataset created successfully!")
print("Dataset size:", df.shape)

df.head()

Dataset created successfully!
Dataset size: (1000, 4)

   Customer_ID  Age  Annual_Spend Region
0            1   56          2006   West
1            2   69          3186  South
2            3   46          4680  South
3            4   32          2175   West
4            5   60           813   East

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Customer_ID   1000 non-null   int64
 1   Age           1000 non-null   int64
 2   Annual_Spend  1000 non-null   int64
 3   Region        1000 non-null   object
dtypes: int64(3), object(1)
memory usage: 31.4+ KB
None

In [10]:
df.describe()

       Customer_ID         Age  Annual_Spend
count  1000.000000  1000.00000   1000.000000
mean    500.500000    43.81900   2548.269000
std     288.819436    14.99103   1410.716047
min       1.000000    18.00000    101.000000
25%     250.750000    31.00000   1347.750000
50%     500.500000    44.00000   2520.000000
75%     750.250000    56.00000   3724.500000
max    1000.000000    69.00000   4995.000000

In [12]:
bins = [0, 1000, 3000, 6000]

labels = [
    'Low Spender',
    'Medium Spender',
    'High Spender'
]

df['Spend_Segment'] = pd.cut(
    df['Annual_Spend'],
    bins=bins,
    labels=labels
)

df.head()

   Customer_ID  Age  Annual_Spend Region   Spend_Segment
0            1   56          2006   West  Medium Spender
1            2   69          3186  South    High Spender
2            3   46          4680  South    High Spender
3            4   32          2175   West  Medium Spender
4            5   60           813   East     Low Spender

In [13]:
print(df['Spend_Segment'].value_counts())

Spend_Segment
High Spender      413
Medium Spender    411
Low Spender       176
Name: count, dtype: int64

In [14]:
print(
    df['Spend_Segment']
    .value_counts(normalize=True)
    .mul(100)
)

Spend_Segment
High Spender      41.3
Medium Spender    41.1
Low Spender       17.6
Name: proportion, dtype: float64

In [15]:
print(df.head(20))

    Customer_ID  Age  Annual_Spend Region   Spend_Segment
0             1   56          2006   West  Medium Spender
1             2   69          3186  South    High Spender
2             3   46          4680  South    High Spender
3             4   32          2175   West  Medium Spender
4             5   60           813   East     Low Spender
5             6   25          1162   West  Medium Spender
6             7   38          2076  South  Medium Spender
7             8   56          1396  North  Medium Spender
8             9   36           225  North     Low Spender
9            10   40          4732   East    High Spender
10           11   28          3696   West    High Spender
11           12   28          3383  North    High Spender
12           13   41          1703   West  Medium Spender
13           14   53           166  South     Low Spender
14           15   57           332  North     Low Spender
15           16   41          2256   East  Medium Spender
16           17   20          1269  South  Medium Spender
17           18   39          2258   East  Medium Spender
18           19   19          4306  South    High Spender
19           20   41          1593  North  Medium Spender

In [16]:
df.to_csv(
    'segmented_customers.csv',
    index=False
)

print("Data successfully processed and exported to CSV!")

Data successfully processed and exported to CSV!

In [17]:
from google.colab import files

files.download('segmented_customers.csv')